* セットアップ手順

** 自動で入れるもの

   install.sh を実行する。

** 手動で入れるもの

   google-chrome, vscode, rustup, sdkman

   それぞれ公式サイトに移動して deb ファイルを手に入れるなりワンライナーを実行してセットアップする。

   - https://www.google.com/intl/ja_ALL/chrome/
   - https://code.visualstudio.com/
   - https://rustup.rs/
   - https://sdkman.io/

*** VSCode

    VSCodeは以下の 2 つの Extensions をインストールする

    - Emacs Keymap
    - Rust (rls)

** 手動で設定するもの

*** HIDPI

    xubuntu だと 144 dpi 程度かなぁ

*** IME(fcitx-mozc)

    xubuntu で普通に入れただけだと自動起動しないみたいなので Session and Startup で fcitx-autostart を autostart に追加する必要があるみたい。

    https://qiita.com/tukiyo3/items/69ce214f25cbecbba9ff

*** dual boot win and ubuntu clock

    Windows と Ubuntu のデュアルブートするときには時計が9時間ずれる問題があるので以下を設定する。
    http://yukihane.hatenablog.com/entry/201605/ubuntu16.04-datetime

    具体的には以下のコマンドを実行する。

    #+BEGIN_SRC sh
sudo timedatectl set-local-rtc 1
    #+END_SRC

*** no capslock

    caps lock を設定する日はないので以下を参考に設定する。

    https://qiita.com/hirooooooaki/items/f404e76c6f171769412a

    /etc/default/keyboard を編集する。

    #+BEGIN_SRC
XKBMODEL="pc105"
XKBLAYOUT="jp"
XKBVARIANT=""
XKBOPTIONS="ctrl:nocaps" 
BACKSPACE="guess"
    #+END_SRC

*** 無変換/変換キーでIMEをtoggleじゃなく変更できるようにする。

    Input Method Configuration -> Global Config

    Show Advanced Option をチェックする

    Activate input method に変換を Inactivate input method に無変換を割り当てる。

    Input Method タブには "Keyboard - Japanese", "Mozc" の２つを設定する。

*** natural scroll

    ThinkPad の touchpad で natural scroll にするには以下の /etc/X11/Xsession.d/80synaptics の設定を入れるのが良い

    https://askubuntu.com/questions/690512/how-to-enable-natural-scrolling-in-xfce4

*** github の 2 要素認証を使ったログイン

    PersonalToken を新たに払い出して以下を設定する。 .netrc のこと。

    https://qiita.com/Asuforce/items/c2fa32e78d0d6fcf015d

*** grub の解像度が細かすぎるのを大きくする

    sudo vi /etc/default/grub

    以下の一行を追加する

    GRUB_GFXMODE=640x480

    sudo grub2-mkconfig -o /boot/grub2/grub.cfg
